import type { WorldDefinition } from './types.js';

export const eberron: WorldDefinition = {
  key: 'eberron',
  label: 'Eberron',
  description: '12 months of 28 days. 7-day week. Default Eberron Campaign Setting calendar.',
  eraLabel: 'YK',
  sunName: 'Arrah',
  defaultDate: { month: 0, day: 1, year: 998 },

  calendar: {
    key: 'eberron',
    label: 'Galifar',
    weekdays: ['Sul', 'Mol', 'Zol', 'Wir', 'Zor', 'Far', 'Sar'],
    monthDays: [28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28],
    namingOverlays: [
      {
        key: 'standard',
        label: 'Galifar',
        monthNames: [
          'Zarantyr', 'Olarune', 'Therendor', 'Eyre',
          'Dravago', 'Nymm', 'Lharvion', 'Barrakas',
          'Rhaan', 'Sypheros', 'Aryth', 'Vult',
        ],
        colorTheme: 'lunar',
      },
      {
        key: 'druidic',
        label: 'Druidic',
        monthNames: [
          'Frostmantle', 'Thornrise', 'Treeborn', 'Rainsong',
          'Arrowfar', 'Sunstride', 'Glitterstream', 'Havenwild',
          'Stormborn', 'Harrowfall', 'Silvermoon', 'Windwhisper',
        ],
        colorTheme: 'druidic',
      },
      {
        key: 'halfling',
        label: 'Halfling',
        monthNames: [
          'Fang', 'Wind', 'Ash', 'Hunt',
          'Song', 'Dust', 'Claw', 'Blood',
          'Horn', 'Heart', 'Spirit', 'Smoke',
        ],
        colorTheme: 'halfling',
      },
      {
        key: 'dwarven',
        label: 'Dwarven',
        monthNames: [
          'Aruk', 'Lurn', 'Ulbar', 'Kharn',
          'Ziir', 'Dwarhuun', 'Jond', 'Sylar',
          'Razagul', 'Thazm', 'Drakhadur', 'Uarth',
        ],
        colorTheme: 'dwarven',
      },
    ],
    defaultOverlayKey: 'standard',
    weekdayProgressionMode: 'continuous_serial',
    intercalaryRenderMode: 'regular_grid',
    dateFormatStyle: 'ordinal_of_month',
  },

  seasons: [
    {
      key: 'eberron',
      names: [
        'Mid-winter', 'Late winter', 'Early spring', 'Mid-spring',
        'Late spring', 'Early summer', 'Mid-summer', 'Late summer',
        'Early autumn', 'Mid-autumn', 'Late autumn', 'Early winter',
      ],
      hemisphereAware: false,
    },
  ],
  defaultSeasonKey: 'eberron',

  moons: {
    label: 'Eberron Moons',
    anchorStrategy: 'per_moon_anchor',
    bodies: [
      {
        key: 'zarantyr',
        name: 'Zarantyr',
        title: 'The Storm Moon',
        color: '#F5F5FA',
        associatedMonth: 1,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 27.32,
        visibilityMode: 'normal',
        data: { plane: 'Kythri', dragonmark: 'Mark of Storm' },
      },
      {
        key: 'olarune',
        name: 'Olarune',
        title: 'The Sentinel Moon',
        color: '#FFC68A',
        associatedMonth: 2,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 30.8052,
        visibilityMode: 'normal',
        data: { plane: 'Lamannia', dragonmark: 'Mark of Sentinel' },
      },
      {
        key: 'therendor',
        name: 'Therendor',
        title: "The Healer's Moon",
        color: '#D3D3D3',
        associatedMonth: 3,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 34.735,
        visibilityMode: 'normal',
        data: { plane: 'Syrania', dragonmark: 'Mark of Healing' },
      },
      {
        key: 'eyre',
        name: 'Eyre',
        title: 'The Anvil',
        color: '#C0C0C0',
        associatedMonth: 4,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 39.1661,
        visibilityMode: 'normal',
        data: { plane: 'Fernia', dragonmark: 'Mark of Making' },
      },
      {
        key: 'dravago',
        name: 'Dravago',
        title: "The Herder's Moon",
        color: '#E6E6FA',
        associatedMonth: 5,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 44.1625,
        visibilityMode: 'normal',
        data: { plane: 'Risia', dragonmark: 'Mark of Handling' },
      },
      {
        key: 'nymm',
        name: 'Nymm',
        title: 'The Crown',
        color: '#FFD96B',
        associatedMonth: 6,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 49.7962,
        visibilityMode: 'normal',
        data: { plane: 'Daanvi', dragonmark: 'Mark of Hospitality' },
      },
      {
        key: 'lharvion',
        name: 'Lharvion',
        title: 'The Eye',
        color: '#F5F5F5',
        associatedMonth: 7,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 56.1487,
        visibilityMode: 'normal',
        data: { plane: 'Xoriat', dragonmark: 'Mark of Detection' },
      },
      {
        key: 'barrakas',
        name: 'Barrakas',
        title: 'The Lantern',
        color: '#DCDCDC',
        associatedMonth: 8,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 63.3115,
        visibilityMode: 'normal',
        data: { plane: 'Irian', dragonmark: 'Mark of Finding' },
      },
      {
        key: 'rhaan',
        name: 'Rhaan',
        title: 'The Book',
        color: '#9AC0FF',
        associatedMonth: 9,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 71.3881,
        visibilityMode: 'normal',
        data: { plane: 'Thelanis', dragonmark: 'Mark of Scribing' },
      },
      {
        key: 'sypheros',
        name: 'Sypheros',
        title: 'The Shadow',
        color: '#696969',
        associatedMonth: 10,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 80.495,
        visibilityMode: 'normal',
        data: { plane: 'Mabar', dragonmark: 'Mark of Shadow' },
      },
      {
        key: 'aryth',
        name: 'Aryth',
        title: 'The Gateway',
        color: '#FF4500',
        associatedMonth: 11,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 90.7637,
        visibilityMode: 'normal',
        data: { plane: 'Dolurrh', dragonmark: 'Mark of Passage' },
      },
      {
        key: 'vult',
        name: 'Vult',
        title: 'The Warding Moon',
        color: '#A9A9A9',
        associatedMonth: 12,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 102.3424,
        visibilityMode: 'normal',
        data: { plane: 'Shavarath', dragonmark: 'Mark of Warding' },
      },
    ],
  },

  eventPacks: [
    {
      key: 'sharn',
      label: 'Sharn',
      events: [
        { name: 'Tain Gala', month: 'all', day: 'first far', color: '#F7E7CE', source: 'sharn' },
        { name: 'Crystalfall', month: 2, day: 9, color: '#D7F3FF', source: 'sharn' },
        { name: 'Day of Ashes', month: 5, day: 3, color: '#B0BEC5', source: 'sharn' },
        { name: 'The Race of Eight Winds', month: 7, day: 23, color: '#006D3C', source: 'sharn' },
      ],
    },
    {
      key: 'khorvaire',
      label: 'Khorvaire',
      events: [
        { name: 'Day of Mourning', month: 2, day: 20, color: '#9E9E9E', source: 'khorvaire' },
        { name: "Galifar's Throne", month: 6, day: 5, color: '#D4AF37', source: 'khorvaire' },
        { name: 'Thronehold', month: 11, day: 11, color: '#E80001', source: 'khorvaire' },
      ],
    },
    {
      key: 'sovereign host',
      label: 'Sovereign Host',
      events: [
        { name: "Onatar's Flame", month: 1, day: 7, color: '#FF6F00', source: 'sovereign host' },
        { name: "Turrant's Gift", month: 2, day: 14, color: '#B8860B', source: 'sovereign host' },
        { name: "Olladra's Feast", month: 2, day: 28, color: '#8BC34A', source: 'sovereign host' },
        { name: "Sun's Blessing", month: 3, day: 15, color: '#FFC107', source: 'sovereign host' },
        { name: "Aureon's Crown", month: 5, day: 26, color: '#283593', source: 'sovereign host' },
        { name: 'Brightblade', month: 6, day: 12, color: '#B71C1C', source: 'sovereign host' },
        { name: "Bounty's Blessing", month: 7, day: 14, color: '#388E3C', source: 'sovereign host' },
        { name: 'The Hunt', month: 8, day: 4, color: '#1B5E20', source: 'sovereign host' },
        { name: "Boldrei's Feast", month: 9, day: 9, color: '#F57C00', source: 'sovereign host' },
        { name: 'Market Day', month: 11, day: 20, color: '#FFD54F', source: 'sovereign host' },
      ],
    },
    {
      key: 'dark six',
      label: 'The Dark Six',
      events: [
        { name: "Shargon's Bargain", month: 4, day: 13, color: '#006064', source: 'dark six' },
        { name: 'Second Skin', month: 6, day: 11, color: '#809E62', source: 'dark six' },
        { name: 'Wildnight', month: 10, day: '18-19', color: '#AD1457', source: 'dark six' },
        { name: 'Long Shadows', month: 12, day: '26-28', color: '#0D0D0D', source: 'dark six' },
      ],
    },
    {
      key: 'silver flame',
      label: 'Silver Flame',
      events: [
        { name: 'Rebirth Eve', month: 1, day: 14, color: '#EAF2FF', source: 'silver flame' },
        { name: "Bright Souls' Day", month: 2, day: 18, color: '#FFF2C6', source: 'silver flame' },
        { name: 'Tirasday', month: 3, day: 5, color: '#DCEBFF', source: 'silver flame' },
        { name: 'Initiation Day', month: 4, day: 11, color: '#C7E3FF', source: 'silver flame' },
        { name: "Baker's Night", month: 5, day: 6, color: '#D8B98F', source: 'silver flame' },
        { name: 'Promisetide', month: 5, day: 28, color: '#BDE3FF', source: 'silver flame' },
        { name: 'First Dawn', month: 6, day: 21, color: '#FFD1A6', source: 'silver flame' },
        { name: 'Silvertide', month: 7, day: 14, color: '#F2F7FF', source: 'silver flame' },
        { name: 'Victory Day', month: 8, day: 9, color: '#B3E5FC', source: 'silver flame' },
        { name: "Fathen's Fall", month: 8, day: 25, color: '#E7ECF5', source: 'silver flame' },
        { name: 'The Ascension', month: 10, day: 1, color: '#E6F0FF', source: 'silver flame' },
        { name: "Saint Valtros's Day", month: 10, day: 25, color: '#E8ECFF', source: 'silver flame' },
        { name: 'Rampartide', month: 11, day: 24, color: '#D6F5D6', source: 'silver flame' },
        { name: 'Khybersef', month: 12, day: 27, color: '#111827', source: 'silver flame' },
        { name: 'Day of Cleansing Fire', month: 'all', day: 'all sul', color: '#F2F7FF', source: 'silver flame' },
      ],
    },
    {
      key: 'stormreach',
      label: 'Stormreach',
      events: [
        { name: 'The Burning Titan', month: 3, day: 1, color: '#FF5722', source: 'stormreach' },
        { name: "Pirate's Moon", month: 5, day: 20, color: '#0E7490', source: 'stormreach' },
        { name: 'The Annual Games', month: 6, day: '1-14', color: '#2E7D32', source: 'stormreach' },
        { name: 'Shacklebreak', month: 11, day: 1, color: '#455A64', source: 'stormreach' },
      ],
    },
  ],

  capabilities: {
    moons: true,
    weather: true,
    planes: true,
    defaultEvents: true,
    worldHooks: true,
  },

  setup: {},
};
