import type { WorldDefinition } from './types.js';

export const faerun: WorldDefinition = {
  key: 'faerunian',
  label: 'Forgotten Realms',
  description:
    '12 months of 30 days, split into three tendays. 5 festival days occur between months. Shieldmeet follows Midsummer every 4 years.',
  eraLabel: 'DR',
  defaultDate: { month: 0, day: 1, year: 1372 },

  calendar: {
    key: 'faerunian',
    label: 'Harptos Calendar',
    weekdays: [
      'Firstday',
      'Secondday',
      'Thirdday',
      'Fourthday',
      'Fifthday',
      'Sixthday',
      'Seventhday',
      'Eighthday',
      'Ninthday',
      'Tenthday',
    ],
    weekdayAbbr: {
      Firstday: '1st',
      Secondday: '2nd',
      Thirdday: '3rd',
      Fourthday: '4th',
      Fifthday: '5th',
      Sixthday: '6th',
      Seventhday: '7th',
      Eighthday: '8th',
      Ninthday: '9th',
      Tenthday: '10th',
    },
    monthDays: [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
    structure: [
      { name: 'Hammer', days: 30, regularIndex: 0 },
      { name: 'Midwinter', days: 1, isIntercalary: true },
      { name: 'Alturiak', days: 30, regularIndex: 1 },
      { name: 'Ches', days: 30, regularIndex: 2 },
      { name: 'Tarsakh', days: 30, regularIndex: 3 },
      { name: 'Greengrass', days: 1, isIntercalary: true },
      { name: 'Mirtul', days: 30, regularIndex: 4 },
      { name: 'Kythorn', days: 30, regularIndex: 5 },
      { name: 'Flamerule', days: 30, regularIndex: 6 },
      { name: 'Midsummer', days: 1, isIntercalary: true },
      { name: 'Shieldmeet', days: 1, isIntercalary: true, leapEvery: 4 },
      { name: 'Eleasis', days: 30, regularIndex: 7 },
      { name: 'Eleint', days: 30, regularIndex: 8 },
      { name: 'Marpenoth', days: 30, regularIndex: 9 },
      { name: 'Uktar', days: 30, regularIndex: 10 },
      { name: 'Highharvestide', days: 1, isIntercalary: true },
      { name: 'Nightal', days: 30, regularIndex: 11 },
      { name: 'Feast of the Moon', days: 1, isIntercalary: true },
    ],
    namingOverlays: [
      {
        key: 'standard',
        label: 'Standard (Dalereckoning)',
        monthNames: [
          'Hammer',
          'Alturiak',
          'Ches',
          'Tarsakh',
          'Mirtul',
          'Kythorn',
          'Flamerule',
          'Eleasis',
          'Eleint',
          'Marpenoth',
          'Uktar',
          'Nightal',
        ],
        colorTheme: 'seasons',
      },
    ],
    defaultOverlayKey: 'standard',
    weekdayProgressionMode: 'month_reset',
    intercalaryRenderMode: 'festival_strip',
    dateFormatStyle: 'ordinal_of_month',
  },

  seasons: [
    {
      key: 'faerun',
      names: [
        'Winter',
        'Winter',
        'Spring',
        'Spring',
        'Spring',
        'Summer',
        'Summer',
        'Summer',
        'Autumn',
        'Autumn',
        'Autumn',
        'Winter',
      ],
      hemisphereAware: true,
    },
  ],
  defaultSeasonKey: 'faerun',

  moons: {
    label: 'Faerunian Moons',
    anchorStrategy: 'per_moon_anchor',
    bodies: [
      {
        key: 'selune',
        name: 'Selûne',
        title: 'The Moonmaiden',
        color: '#C8D8F0',
        associatedMonth: null,
        phaseMode: 'standard_phase',
        cycleMode: 'fixed',
        baseCycleDays: 30.4375,
        visibilityMode: 'normal',
        data: {
          diameter: 2000,
          distance: 183000,
          inclination: 5.1,
          eccentricity: 0.054,
          albedo: 0.25,
          epochSeed: {
            defaultSeed: 'selune',
            referenceDate: { year: 1372, month: 1, day: 1 },
          },
          loreNote:
            'Full at midnight Hammer 1, 1372 DR. Trailed by the Tears of Selûne. Associated with lycanthropy, divination, navigation, and tides.',
          deity: 'Selûne',
        },
      },
    ],
  },

  capabilities: {
    moons: true,
    weather: true,
    planes: false,
    defaultEvents: false,
    worldHooks: false,
  },

  setup: {},
};
